#!/usr/bin/env bash
# Build the tree that goes to the public repository.
#
# The public repo is a snapshot, not a mirror: pushing the development history
# would expose everything ever committed, and deleting a file afterwards does
# not un-index it. So this produces a clean tree from the current commit, drops
# what must not be public, and repoints the install URLs at the public repo.
#
# Usage:
#   bash scripts/build_public_snapshot.sh /path/to/output
#
# Then, in the output directory:
#   git init -b main && git add -A && git commit && git push
set -euo pipefail

OUT="${1:?usage: build_public_snapshot.sh <output-dir>}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
ROOT="$(git -C "$SCRIPT_DIR/.." rev-parse --show-toplevel)"
PUBLIC_REPO="${SKINSCOUT_PUBLIC_REPO:-kangk1204/SkinScout_public}"
PRIVATE_REPO="${SKINSCOUT_PRIVATE_REPO:-kangk1204/SkinScout_public}"

# Files that must never reach the public repository.
#   report_email.sh  — a recipient address, hostname, Tailscale/LAN IP, and
#                      app-password setup instructions
#   review_dump_*    — raw working review dumps whose defect lists are largely
#                      fixed; read cold they describe problems that no longer
#                      exist
#
# Third-party database records. This repository is Apache-2.0, so row-level
# data taken from ChEMBL (CC BY-SA 3.0), BindingDB, PubChem, and the
# Therapeutics Data Commons "skin_reaction" benchmark must not be republished
# inside it: the panels and parquet/CSV exports cannot carry the per-record
# attribution the source licences require, and the licences do not cleanly
# translate to the repo's own. The panels remain rebuildable from the sources
# cited in docs/ and LICENSE_POLICY.md. Kept on purpose: data/compound_names/
# (CosIng) feeds the workbench name search, data/curation/skin_target_worklist*
# is self-authored, and data/holo_transplant/ is a CC-BY-4.0 AlphaFold-derivative
# whose attribution the README already carries.
EXCLUDE=(
    "scripts/report_email.sh"
    "review_dump_01.txt"
    "review_dump_02.txt"
    # Internal development specifications. They describe how the repository was
    # assembled rather than what it does, and they are not product documentation.
    "INSTRUCTIONS_v2.md"
    "INSTRUCTIONS_v2_bootstrap.md"
    # A review-coordination record, not an audit of the product.
    "docs/SKINSCOUT_EXPERT_LINE_BY_LINE_AUDIT_20260904.md"
    # ChEMBL / BindingDB row-level activity records
    "data/pocket_cold_panel_202608"
    "data/transfer_reachable_panel_202608"
    # chembl37-snapshot-evidence truth set plus docking outputs
    "data/validation/rerank_band_20260828"
    # Therapeutics Data Commons skin_reaction benchmark
    "data/validation/skin_sens_benchmark_20260830"
    # PubChem probe caches
    "data/curation/pubchem_probe_cache.json"
    "data/curation/pubchem_probe_cache_medium.json"
)

# Resolve every ancestor before creating anything; markers do not make a home,
# source checkout, symlink, or independently initialized Git repository safe.
case "$OUT" in
    ""|/|/bin|/boot|/dev|/etc|/home|/lib*|/opt|/proc|/root|/run|/sbin|/srv|/sys|/tmp|/usr|/var)
        echo "refusing to use a system path as the output directory: $OUT" >&2
        exit 1 ;;
esac
OUT="$(python3 - "$OUT" "$ROOT" <<'VALIDATE'
import os, sys
from pathlib import Path

raw = Path(os.path.abspath(sys.argv[1]))
root = Path(sys.argv[2]).resolve()
for part in (raw, *raw.parents):
    if part.is_symlink():
        raise SystemExit(f"refusing symlink output path: {part}")
out = raw.resolve()
home = Path.home().resolve()
system = {Path(p) for p in ('/', '/bin', '/boot', '/dev', '/etc', '/home', '/lib', '/lib64', '/opt', '/proc', '/root', '/run', '/sbin', '/srv', '/sys', '/tmp', '/usr', '/var')}
if out in system:
    raise SystemExit(f"refusing system path: {out}")
if out == home or out in home.parents or out == root or out in root.parents:
    raise SystemExit(f"refusing home/repository or ancestor as output: {out}")
if out.exists():
    marker = out / '.skinscout-public-snapshot'
    expected = 'Generated by scripts/build_public_snapshot.sh. Safe to delete.\n'
    if not out.is_dir() or marker.is_symlink() or not marker.is_file() or marker.read_text() != expected:
        raise SystemExit(f"refusing to replace {out}: it is not a SkinScout snapshot")
    if (out / '.git').exists():
        raise SystemExit(f"refusing to replace an initialized repository: {out}")
print(out)
VALIDATE
)"
DESTINATION="$OUT"
mkdir -p "$(dirname "$DESTINATION")"
OUT="$(mktemp -d "${DESTINATION}.building.XXXXXXXX")"
# Build completely before replacing a prior snapshot. Preserve the old tree
# under a unique backup path so a later export can always be undone.
printf 'Generated by scripts/build_public_snapshot.sh. Safe to delete.\n' \
    > "$OUT/.skinscout-public-snapshot"
git -C "$ROOT" archive HEAD | tar -x -C "$OUT"

for path in "${EXCLUDE[@]}"; do
    rm -rf -- "$OUT/$path"
done

# Local exclusions. Some files must never be published but their names cannot
# appear in this script either - the script itself is published, so listing a
# name here would publish exactly what it is meant to hide (the same trap the
# redaction step below fell into once). Names live in a local, uncommitted file
# under the git dir and are read at build time. One path per line; `#` starts a
# comment. Override the location with SKINSCOUT_LOCAL_EXCLUDE.
LOCAL_EXCLUDE="${SKINSCOUT_LOCAL_EXCLUDE:-$(git -C "$ROOT" rev-parse --absolute-git-dir)/info/public-exclude}"
if [[ -f "$LOCAL_EXCLUDE" ]]; then
    while IFS= read -r local_path; do
        if [[ -z "$local_path" || "$local_path" == \#* ]]; then
            continue
        fi
        rm -rf -- "$OUT/$local_path"
    done < "$LOCAL_EXCLUDE"
    echo "  applied local exclusion list ($(grep -cvE '^[[:space:]]*(#|$)' "$LOCAL_EXCLUDE" | tr -d ' ') path(s))"
fi

# The one-line install and the git clone inside it point at the private repo,
# which 404s for anyone who only has the public one.
grep -rl "$PRIVATE_REPO" "$OUT" 2>/dev/null | while read -r file; do
    case "$file" in
        # Sigstore trust policies pin which GitHub Actions workflow may sign a
        # release. Repointing them would make the policy accept signatures from
        # a repo that is not the signer, which weakens it rather than fixing it.
        *"/compose/"*"-trust-policy.json"|*"/compose/image-policy.json") continue ;;
    esac
    # PUBLIC_REPO는 PRIVATE_REPO를 접두어로 포함하므로 단순 치환은 이미 공개된
    # 이름까지 SkinScout_public_public으로 바꿔 버린다. _public 접미어를 먼저
    # 자리표시자로 보호했다가 되돌린다.
    sed -i "s|${PRIVATE_REPO}_public|kangk1204/SkinScout_public|g; s|$PRIVATE_REPO|$PUBLIC_REPO|g; s|kangk1204/SkinScout_public|${PUBLIC_REPO}|g" "$file"
done

# 파일을 지우는 것만으로는 부족하다. report_email.sh는 뺐지만, 감사 문서가 그
# 내용을 인용하면서 개인 주소를 그대로 적어 두었다. 지운 파일의 내용이 다른 파일에
# 남아 있는지까지 봐야 한다.
#
# 가릴 문자열은 **제외 대상 파일에서 읽어낸다**. 여기에 직접 적으면 이 스크립트와
# 그 테스트가 공개본에 함께 실리면서, 가리려던 주소를 정작 자기가 게시하게 된다 -
# 처음에 그렇게 만들었다가 스냅샷을 검사하고 나서야 알았다.
python3 - "$OUT" "$ROOT" "${EXCLUDE[@]}" <<'REDACT'
import re, subprocess, sys
from pathlib import Path

out = Path(sys.argv[1])
root = Path(sys.argv[2])

EMAIL = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
IPV4 = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")
# 공개 저장소·문서에 정상적으로 등장하는 것들은 가리지 않는다.
KEEP_EMAIL = re.compile(r"@(?:users\.noreply\.github\.com|noreply\.|example\.(?:com|org|test|net)|[a-z0-9-]*\.)?skinscout\.example")
KEEP_IP = re.compile(r"^(?:0\.0\.0\.0|127\.0\.0\.1|255\.|8\.8\.8\.8)")

secrets: set[str] = set()
for name in sys.argv[3:]:
    source = root / name
    # The export is HEAD, while the working tree can already have redacted or
    # removed the identifiers. Inspect both generations for redaction values.
    committed = subprocess.run(['git', '-C', str(root), 'show', f'HEAD:{name}'], capture_output=True, text=True, encoding='utf-8', errors='replace', check=False)
    try:
        text = (source.read_text(encoding="utf-8", errors="ignore") if source.is_file() else '') + '\n' + (committed.stdout if committed.returncode == 0 else '')
    except OSError:
        continue
    for hit in EMAIL.findall(text):
        if not KEEP_EMAIL.search(hit):
            secrets.add(hit)
    for hit in IPV4.findall(text):
        if not KEEP_IP.match(hit):
            secrets.add(hit)

# 제외 대상 파일만 쓸면 안 된다. 그 값이 이미 코드에서 변수·정규식으로 바뀌어
# '정리'돼 버리면, 이 단계는 아무것도 안 하고 넘어간다. 그런데 감사 문서는 그
# 주소를 본문에 그대로 인용해 두었을 수 있다. 제외 파일이 깨끗해진 순간 그 가드는
# 조용히 꺼지고 주소가 공개본에 실린다. 그래서 **출력 트리 자체**를 정규식으로
# 훑어 개인 식별자를 직접 찾아낸다. 의도적으로 심어 둔 placeholder
# (example.*, @skinscout.example)는 KEEP_EMAIL이 걸러 준다.
for path in out.rglob("*"):
    if not path.is_file() or path.suffix not in {
        ".md", ".py", ".sh", ".json", ".yaml", ".yml", ".txt", ".html", ".js", ".css"
    }:
        continue
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        continue
    for hit in EMAIL.findall(text):
        if not KEEP_EMAIL.search(hit):
            secrets.add(hit)
    for hit in IPV4.findall(text):
        if not KEEP_IP.match(hit):
            secrets.add(hit)

changed = 0
if secrets:
    # 긴 것부터 바꿔야 짧은 것이 긴 것의 일부를 먼저 먹지 않는다.
    ordered = sorted(secrets, key=len, reverse=True)
    for path in out.rglob("*"):
        if not path.is_file() or path.suffix not in {
            ".md", ".py", ".sh", ".json", ".yaml", ".yml", ".txt", ".html", ".js", ".css"
        }:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        new_text = text
        for secret in ordered:
            label = "<개인 주소>" if "@" in secret else "<사설 IP>"
            new_text = new_text.replace(secret, label)
        if new_text != text:
            path.write_text(new_text, encoding="utf-8")
            changed += 1
            print(f"  가림: {path.relative_to(out)}")

print(f"  가릴 식별자 {len(secrets)}개(제외 파일+출력 트리 스캔), {changed}개 파일에서 가림")
REDACT

python3 - "$OUT" <<'PY'
import sys
from pathlib import Path

out = Path(sys.argv[1])
readme = out / "README.md"
text = readme.read_text(encoding="utf-8")
note = """> **이 저장소는 공개본입니다.** 개인 알림 스크립트 하나와 작업용 검토 덤프 두 개를
> 뺐습니다. 앞의 것에는 수신 주소와 호스트 정보가, 뒤의 것에는 대부분 이미 고친 결함
> 목록이 들어 있어서 그대로 읽으면 오해하기 쉽습니다. 저장소를 만든 과정을 적은 내부
> 개발 문서 세 개도 뺐습니다 - 도구 설명이 아니라 작업 기록입니다.
>
> 코드와 문서는 전부 그대로 두었습니다. 다만 제3자 데이터베이스에서 가져온 패널·벤치마크
> 데이터(차가운 패널, 전이 측정 쌍, 리랭크 진실값, 감작 벤치마크, PubChem Probe 캐시)는
> 원천 라이선스 때문에 공개본에서 뺐습니다. 이 저장소의 Apache-2.0만으로는 그 데이터까지
> 함께 배포할 수 없기 때문입니다. 빠진 패널은 문서에 적어 둔 원천에서 다시 만들면 됩니다.
> `docs/` 아래 감사 보고서도 뺐다가 다시 넣었는데, 이 도구가 무엇을 못 하는지 적어둔
> 문서라 빠지면 오히려 곤란합니다.

"""
anchor = "## 실험 연구자라면 여기부터"
if note not in text:
    text = text.replace(anchor, note + anchor, 1)
    readme.write_text(text, encoding="utf-8")
    print("  README: 공개본 안내 추가")
PY

if [ -e "$DESTINATION" ]; then
    BACKUP="$(mktemp -d "${DESTINATION}.previous.XXXXXXXX")"
    rmdir "$BACKUP"
    mv -T -- "$DESTINATION" "$BACKUP"
    echo "previous snapshot preserved at $BACKUP"
fi
mv -T -- "$OUT" "$DESTINATION"
echo "wrote $DESTINATION ($(find "$DESTINATION" -type f | wc -l) files)"
